-- MySQL Script generated by MySQL Workbench
-- 12/19/14 02:28:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SmartForSalesDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SmartForSalesDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SmartForSalesDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `SmartForSalesDB` ;

-- -----------------------------------------------------
-- Table `SmartForSalesDB`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SmartForSalesDB`.`Usuario` (
  `idUsuario` INT(13) NOT NULL,
  `usuario` VARCHAR(65) NULL,
  `password` VARCHAR(45) NULL,
  `nombre` VARCHAR(25) NULL,
  `apellidos` VARCHAR(25) NULL,
  `direccion` TEXT(120) NULL,
  `telefono` VARCHAR(25) NULL,
  `email` VARCHAR(120) NULL,
  `codigopostal` VARCHAR(25) NULL,
  `puesto` VARCHAR(45) NULL,
  `permisos` TEXT NULL,
  `presupuesto` FLOAT(8) NULL,
  `sueldo` FLOAT(8) NULL,
  `horario` VARCHAR(25) NULL,
  `logged_in` TINYINT(1) NULL,
  `EMPRESA_idEmpresa` INT(13) NOT NULL,
  PRIMARY KEY (`idUsuario`, `EMPRESA_idEmpresa`),
  INDEX `fk_Usuario_Empresa_idx` (`EMPRESA_idEmpresa` ASC),
  CONSTRAINT `fk_Usuario_Empresa`
    FOREIGN KEY (`EMPRESA_idEmpresa`)
    REFERENCES `SmartForSalesDB`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmartForSalesDB`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SmartForSalesDB`.`Empresa` (
  `idEmpresa` INT(13) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NULL,
  `gerente` VARCHAR(65) NULL,
  `idGerente` INT(13) NULL,
  `tipoIndustria` VARCHAR(45) NULL,
  `servicios` TEXT NULL,
  `rfc` VARCHAR(25) NULL,
  `pais` VARCHAR(25) NULL,
  `denominacion` VARCHAR(25) NULL,
  `estado` VARCHAR(25) NULL,
  `ciudad` VARCHAR(25) NULL,
  `telefono` VARCHAR(25) NULL,
  `direccion` TEXT(120) NULL,
  `codigopostal` VARCHAR(25) NULL,
  `email` VARCHAR(120) NULL,
  `fax` VARCHAR(75) NULL,
  `website` TEXT(265) NULL,
  `urlLogotipo` TEXT(265) NULL,
  `dolar` FLOAT(8) NULL,
  `euro` FLOAT(8) NULL,
  `noEmpleados` INT(5) NULL,
  `GERENTE_idUsuario` INT(13) NULL,
  PRIMARY KEY (`idEmpresa`),
  INDEX `fk_Empresa_Usuario1_idx` (`GERENTE_idUsuario` ASC),
  CONSTRAINT `fk_Empresa_Usuario1`
    FOREIGN KEY (`GERENTE_idUsuario`)
    REFERENCES `SmartForSalesDB`.`Usuario` (`EMPRESA_idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmartForSalesDB`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SmartForSalesDB`.`Producto` (
  `idProducto` INT(13) NOT NULL,
  `codigobarra` INT(15) NULL,
  `nombre` VARCHAR(25) NULL,
  `descripcion` TEXT NULL,
  `stock` INT(8) NULL,
  `existenciaActual` INT(8) NULL,
  `precioUnitario` FLOAT(8) NULL,
  `fechaCaducidad` VARCHAR(25) NULL,
  `talla` VARCHAR(25) NULL,
  `ingredientes` TEXT NULL,
  `medida` VARCHAR(15) NULL,
  `textura` TEXT NULL,
  `tela` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `materiales` TEXT NULL,
  `accesorios` TEXT NULL,
  `cargoExtra` FLOAT(8) NULL,
  `motivoCargo` TEXT(143) NULL,
  `IVA` FLOAT(8) NULL,
  `cargoIVA` FLOAT(8) NULL,
  `precioFinal` FLOAT(8) NULL,
  `urlImagen` TEXT(265) NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmartForSalesDB`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SmartForSalesDB`.`Venta` (
  `idVenta` INT(13) NOT NULL AUTO_INCREMENT,
  `ATIENDE_idUsuario` INT(13) NULL,
  `nombreEmpleado` VARCHAR(65) NULL,
  `idCliente` INT(13) NULL,
  `nombreCliente` VARCHAR(65) NULL,
  `sucursal` VARCHAR(120) NULL,
  `listaProductos` TEXT NULL,
  `cantidadProductos` INT(8) NULL,
  `subtotal` FLOAT(8) NULL,
  `ivaIncluido` TINYINT(1) NULL,
  `IVA` FLOAT(8) NULL,
  `cargoIVA` FLOAT(8) NULL,
  `cargoExtra` FLOAT(8) NULL,
  `montoCargoExtra` FLOAT(8) NULL,
  `aplicaPromocion` TINYINT(1) NULL,
  `descuento` FLOAT(8) NULL,
  `montoDescuento` FLOAT(8) NULL,
  `total` FLOAT(8) NULL,
  `fecha` VARCHAR(45) NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Venta_Usuario1_idx` (`ATIENDE_idUsuario` ASC),
  CONSTRAINT `fk_Venta_Usuario1`
    FOREIGN KEY (`ATIENDE_idUsuario`)
    REFERENCES `SmartForSalesDB`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
